scale: 4
phase: 1
train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ../datasets/DIV2K_train_sub/HR/x4
      root_path_2: ../datasets/DIV2K_train_sub/LR/x4
  wrapper:
    name: sr-implicit-paired
    args:
      augment:
      - hflip
      - vflip
      - dflip
  batch_size: 16
valid_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ../datasets/DIV2K_valid_sub/HR/x4
      root_path_2: ../datasets/DIV2K_valid_sub/LR/x4
  wrapper:
    name: sr-implicit-paired
    args:
      augment: null
test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ../datasets/Test2K/HR/x4
      root_path_2: ../datasets/Test2K/LR/x4
  wrapper:
    name: sr-implicit-paired
    args:
      augment: null
psnr_type: rgb
patch_size: 32
step: 28
data_norm:
  mean:
  - 0.4488
  - 0.4371
  - 0.404
  std:
  - 1.0
  - 1.0
  - 1.0
model:
  name: pcsr-phase1
  args:
    encoder_spec:
      name: carn
      args:
        nf: 40
        scale: 4
        no_upsampling: true
    light_sampler_spec:
      name: liif-sampler
      args:
        imnet_spec:
          name: mlp
          args:
            hidden_list:
            - 40
            - 40
    heavy_sampler_spec:
      name: liif-sampler
      args:
        imnet_spec:
          name: mlp
          args:
            hidden_list:
            - 86
            - 86
            - 86
            - 86
        feat_unfold: true
optimizer:
  name: adam
  args:
    lr: 0.0002
lr_scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 500000
    eta_min: 1.0e-07
iter_max: 500000
iter_print: 1000
iter_val: 50000
iter_save: 100000
init_path: save/carn-liif-pcsr-x4-phase0/iter_last.pth
resume_path: save/carn-liif-pcsr-x4-phase1/iter_last.pth
gpu: '1'
resume: false
